-- MySQL Script generated by MySQL Workbench
-- lun. 08 oct. 2018 19:10:01 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boutique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boutique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boutique` DEFAULT CHARACTER SET utf8 ;
USE `boutique` ;

-- -----------------------------------------------------
-- Table `boutique`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`adresse` (
  `ID` INT NOT NULL,
  `members_id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `code_postal` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`produit_achetés`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`produit_achetés` (
  `achat_id` INT NOT NULL,
  `produit_id` INT NOT NULL,
  `numbers` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`achat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`achat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`achat` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `members_id` VARCHAR(45) NOT NULL,
  `totalprice` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`panier` (
  `members_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `numbers` INT NULL DEFAULT 1,
  PRIMARY KEY (`members_id`, `product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`members` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSEWORD` VARCHAR(255) NOT NULL,
  `register_date` DATETIME NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`promotions` (
  `ID` INT NOT NULL,
  `product_id` INT NOT NULL,
  `pourcentage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`produits` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `price` FLOAT NULL,
  `name` VARCHAR(45) NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`CATEGORIES` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boutique`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boutique`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
